apiVersion: v1
kind: Pod
metadata: 
 name: redis_springmusic 
spec:
 containers:
 - name: animals 
   image: supergiantkir/animals:bear 
   volumeMounts:
    - name: animals-persistent-storage
      mountPath: /app/data
   ports: 
   - containerPort: 80
 - name: springapp
   image: yanivomc/spring-music:latest
   volumeMounts:
    - name: springapp-persistent-storage
      mountPath: /app/data
   ports: 
   - containerPort: 8080
  volumes:
  - name: demo_volume
    hostPath:
      path: /tmp/files
