apiVersion: v1
kind: Pod
metadata: 
 name: redis_springmusic 
spec:
 containers:
 - name: animals 
   image: supergiantkir/animals:bear 
   volumeMounts:
 i   - name: demo-volume
      mountPath: /app/data
   ports: 
   - containerPort: 80
 - name: springapp
   image: yanivomc/spring-music:latest
   volumeMounts:
    - name: demo-volume
      mountPath: /app/data
   ports: 
   - containerPort: 8080
 volumes:
 - name: demo-volume
   hostPath:
     path: /tmp/files
